### ISSUE TITLE
installation on Mac Darwin running into warning

### ISSUE THREAD

**Issue by tonytamsf** [YahooArchive/mojito#114]
sudo npm install --force -g .
YHdrs library could not be loadedError: Cannot find or access denied to the module 'yhdrs'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:271:25)
    at http.js:1007:31
    at NativeModule.compile (node.js:458:5)
    at Function.require (node.js:426:18)
    at Function._load (module.js:296:25)
    at require (module.js:366:19)
    at request (/usr/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:125:23)
    at GET (/usr/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:245:3)
    at get_ (/usr/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:52:3)
Can't load YIV:Error: Cannot find or access denied to the module 'mod_yiv'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:271:25)
    at ensure_yiv (http.js:1020:38)
    at http.js:1033:2
    at NativeModule.compile (node.js:458:5)
    at Function.require (node.js:426:18)
    at Function._load (module.js:296:25)
    at require (module.js:366:19)
    at request (/usr/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:125:23)
    at GET (/usr/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:245:3)

/home/y/bin/mojito -> /home/y/lib/node_modules/mojito/bin/mojito
mojito@0.3.1 /home/y/lib/node_modules/mojito 
├── mime@1.2.4
├── express@2.5.2 (qs@0.4.2 mkdirp@0.0.7)
├── connect@1.8.2 (qs@0.4.2 formidable@1.0.9)
├── jsdom@0.2.0 (request@2.9.153 htmlparser@1.7.5)
└── yui3@0.7.12

**Comment by drewfish** [comment]
Installing from the NPM registry works fine.  I just tried installing from the github repo too, and it worked.

```
git clone git://github.com/yahoo/mojito.git
cd mojito/source
sudo npm install -g .
npm ls -g
```

I'm using npm@1.0.106 and node.js version 0.4.9.

**Comment by drewfish** [comment]
Please reopen with details of the steps you are taking if you are still running into trouble.

**Comment by tonytamsf** [comment]
beingmaster-lm:hello tonytam$ npm -v
1.0.17

beingmaster-lm:hello tonytam$ node -v
v0.4.9-pre

I will to replicate 
beingmaster-lm:hello tonytam$ uname -a
Darwin beingmaster-lm 10.8.0 Darwin Kernel Version 10.8.0: Tue Jun  7 16:33:36 PDT 2011; root:xnu-1504.15.3~1/RELEASE_I386 i386
