### ISSUE TITLE
Files with client affinity in the binders directory break backwards-compatibility in 0.3.25

### ISSUE THREAD

**Issue by ekashida** [YahooArchive/mojito#188]
The context key "device=client" has an undefined value when registering binders in the server environment:
https://github.com/yahoo/mojito/blob/master/source/lib/store.server.js#L346

I have confirmed that this is not an issue when changing the file name to exclude the client affinity.

✖ There was an error starting the application:

✖ Cannot set property 'binder-gallery/gallery-bootstrap-engine' of undefined
    TypeError: Cannot set property 'binder-gallery/gallery-bootstrap-engine' of undefined
    at Object.preload (/Users/keugene/.nvm/v0.6.9/lib/node_modules/mojito/lib/store.server.js:346:54)
    at Object.addMojitoToExpressApp (/Users/keugene/.nvm/v0.6.9/lib/node_modules/mojito/lib/index.js:130:15)
    at Object.createServer (/Users/keugene/.nvm/v0.6.9/lib/node_modules/mojito/lib/index.js:326:14)
    at Object.start (/Users/keugene/.nvm/v0.6.9/lib/node_modules/mojito/lib/management/utils.js:483:56)
    at Object.run (/Users/keugene/.nvm/v0.6.9/lib/node_modules/mojito/lib/management/commands/start.js:105:9)
    at main (/Users/keugene/.nvm/v0.6.9/lib/node_modules/mojito/lib/management/cli.js:124:13)
    at Object.<anonymous> (/Users/keugene/.nvm/v0.6.9/lib/node_modules/mojito/lib/management/cli.js:136:1)
    at Module._compile (module.js:444:26)
    at Object..js (module.js:462:10)
    at Module.load (module.js:351:31)

**Comment by drewfish** [comment]
Binders always have client affinity, so the affinity should not be specified in the binder's filename.

**Comment by ekashida** [comment]
Makes sense. I was a little more concerned about the fact that this part of the code hadn't been touched but I was getting this error. I'll make the appropriate changes on my end.
