### ISSUE TITLE
mojit test templates are broken for archetypes "Default" and "Full"

### ISSUE THREAD

**Issue by imalberto** [YahooArchive/mojito#190]
Tested on: 0.3.25

mojito create mojit DefaultBroken
mojito test mojit mojits/DefaultBroken

✖  FAILED       DefaultBroken-tests :: DefaultBroken user tests :: test mojit
⚑ deferred      DefaultBrokenBinderIndex-tests :: DefaultBroken index binder tests :: TODO: test update id
✔  passed       DefaultBrokenModelFoo-tests :: DefaultBrokenModelFoo user tests :: test mojit model
# FAILURE DETAILS:

DefaultBroken-tests :: DefaultBroken user tests :: test mojit
Values should be the same.
Expected: {"x":"y"} (string)
Actual: [object Object](object)

Total tests: 3  ✔ Passed: 1     ⚑ Deferred: 1   ✖ Failed: 1     33% pass rate
## 

mojito create mojit full FullBroken
mojito test mojit mojits/FullBroken

✖  FAILED       FullBroken-tests :: FullBroken user tests :: test mojit
⚑ deferred      FullBrokenBinderIndex-tests :: FullBroken index binder tests :: TODO: test update id
✖  FAILED       FullBrokenModel-tests :: FullBroken model user tests :: test mojit model
# FAILURE DETAILS:

FullBroken-tests :: FullBroken user tests :: test mojit
TypeError: Cannot read property 'index' of undefined
    at [object Object].test mojit (/Users/albertoc/fs/stage/github/test_mojito/TestApp/mojits/FullBroken/tests/controller.server-tests.js:26:36)
    at [object Object]._resumeTest (/Users/albertoc/fs/stage/github/mojito/source/lib/tests/harness/lib/yuitest/javascript/build/yuitest/yuitest-node.js:2796:29)
    at [object Object]._runTest (/Users/albertoc/fs/stage/github/mojito/source/lib/tests/harness/lib/yuitest/javascript/build/yuitest/yuitest-node.js:3002:26)
    at [object Object]._run (/Users/albertoc/fs/stage/github/mojito/source/lib/tests/harness/lib/yuitest/javascript/build/yuitest/yuitest-node.js:2753:30)
    at Timer.callback (/Users/albertoc/fs/stage/github/mojito/source/lib/tests/harness/lib/yuitest/javascript/build/yuitest/yuitest-node.js:2747:52)

FullBrokenModel-tests :: FullBroken model user tests :: test mojit model
TypeError: Cannot read property 'getMessage' of undefined
    at [object Object].test mojit model (/Users/albertoc/fs/stage/github/test_mojito/TestApp/mojits/FullBroken/tests/models/model.server-tests.js:24:31)
    at [object Object]._resumeTest (/Users/albertoc/fs/stage/github/mojito/source/lib/tests/harness/lib/yuitest/javascript/build/yuitest/yuitest-node.js:2796:29)
    at [object Object]._runTest (/Users/albertoc/fs/stage/github/mojito/source/lib/tests/harness/lib/yuitest/javascript/build/yuitest/yuitest-node.js:3002:26)
    at [object Object]._run (/Users/albertoc/fs/stage/github/mojito/source/lib/tests/harness/lib/yuitest/javascript/build/yuitest/yuitest-node.js:2753:30)
    at Timer.callback (/Users/albertoc/fs/stage/github/mojito/source/lib/tests/harness/lib/yuitest/javascript/build/yuitest/yuitest-node.js:2747:52)

Total tests: 3  ✔ Passed: 0     ⚑ Deferred: 1   ✖ Failed: 2     0% pass rate

**Comment by imalberto** [comment]
See pull request here: https://github.com/yahoo/mojito/pull/192

**Comment by isao** [comment]
Awesome. Pull request accepted on 20ba639c, closing.

**Comment by dmitris** [comment]
I think it is still a problem - the test fails since see https://github.com/yahoo/mojito/issues/255 and the proposed fix https://github.com/dmitris/mojito/commit/b6b646f87cb001daa77b11fe7d503485fc5add46
