### ISSUE TITLE
Mojito 0.4.0 Test fails for Node Modules

### ISSUE THREAD

**Issue by vinitj** [YahooArchive/mojito#351]
I am trying to install Mojito 0.4.0 in my dev box. All installation works fine but when I run the command ‘sudo mojito test –c –v app .  ’ test cases fails for node modules which are not written by us due to which our commit fails.

Can someone please let me know why mojito test command running the test cases of node_modules folder or is there any way to avoid this in dev as well as Manhattan environment ?

Errors which I am getting in my dev box (same as Manhattan environment)::-

warn:: command cannot be defined in a mojit. skipping /home/username/Mojito30/cricket/node_modules/mojito-shaker/commands/shake.js
error: (addon-rs-yui):
exports is not defined
ReferenceError: exports is not defined
    at /home/username/Mojito30/cricket/node_modules/memcached/tests/common.js:9:1
    at RSAddonYUI._captureYUIModuleDetails (/home/username/Mojito30/cricket/node_modules/mojito/lib/app/addons/rs/yui.server.js:614:23)
    at RSAddonYUI.parseResourceVersion (/home/username/Mojito30/cricket/node_modules/mojito/lib/app/addons/rs/yui.server.js:222:22)
    at ResourceStore.<anonymous> (/home/y/lib/node_modules/mojito/node_modules/yui/oop/oop-min.js:7:2282)
    at [object Object].exec (/home/y/lib/node_modules/mojito/node_modules/yui/event-custom-base/event-custom-base-min.js:7:1138)
    at ResourceStore.parseResourceVersion (/home/y/lib/node_modules/mojito/node_modules/yui/event-custom-base/event-custom-base-min.js:7:535)
    at /home/y/lib/node_modules/mojito/lib/store.server.js:1787:30
    at ResourceStore._walkDirRecursive (/home/y/lib/node_modules/mojito/lib/store.server.js:1875:21)
    at ResourceStore._walkDirRecursive (/home/y/lib/node_modules/mojito/lib/store.server.js:1878:30)
    at ResourceStore._findResourcesByConvention (/home/y/lib/node_modules/mojito/lib/store.server.js:1750:18)

/home/username/Mojito30/cricket/node_modules/mojito/lib/app/addons/rs/yui.server.js:223
                res.name = res.yui.name;
                                  ^
TypeError: Cannot read property 'name' of undefined
    at RSAddonYUI.parseResourceVersion (/home/username/Mojito30/cricket/node_modules/mojito/lib/app/addons/rs/yui.server.js:223:35)
    at ResourceStore.<anonymous> (/home/y/lib/node_modules/mojito/node_modules/yui/oop/oop-min.js:7:2282)
   at [object Object].exec (/home/y/lib/node_modules/mojito/node_modules/yui/event-custom-base/event-custom-base-min.js:7:1138)
    at ResourceStore.parseResourceVersion (/home/y/lib/node_modules/mojito/node_modules/yui/event-custom-base/event-custom-base-min.js:7:535)
    at /home/y/lib/node_modules/mojito/lib/store.server.js:1787:30
    at ResourceStore._walkDirRecursive (/home/y/lib/node_modules/mojito/lib/store.server.js:1875:21)
    at ResourceStore._walkDirRecursive (/home/y/lib/node_modules/mojito/lib/store.server.js:1878:30)
    at ResourceStore._findResourcesByConvention (/home/y/lib/node_modules/mojito/lib/store.server.js:1750:18)
   at ResourceStore._preloadDirMojit (/home/y/lib/node_modules/mojito/lib/store.server.js:1661:25)
    at ResourceStore._preloadDirMojits (/home/y/lib/node_modules/mojito/lib/store.server.js:1581:22)

**Comment by isao** [comment]
Hi Vinit, just to confirm, the same code and command works for 0.3.x?

**Comment by vinitj** [comment]
@isao same code and command works for Mojito 0.3.30

**Comment by jenny** [comment]
This is out of scope and unsupported (even if it previously worked). Please clarify if I'm misunderstanding the lack of value of such a feature. 

/cc @rwaldura
