### ISSUE TITLE
mojito 0.4 creates apps that pull in mojito 0.3 as dependency, which breaks unit tests (and more?)

### ISSUE THREAD

**Issue by FabianFrank** [YahooArchive/mojito#352]
steps to reproduce
$ npm install mojito@0.4.0 -g
$ mojito create app test
$ cat test/package.json
...
    "dependencies": {
        "mojito": ">= 0.1.0"
    },
...
$ npm install .
npm WARN package.json test@0.0.1 No README.md file found!
npm http GET https://registry.npmjs.org/mojito
npm http 200 https://registry.npmjs.org/mojito
npm http GET https://registry.npmjs.org/mojito/-/mojito-0.3.30.tgz
npm http 200 https://registry.npmjs.org/mojito/-/mojito-0.3.30.tgz
...

when trying to test this app:
$ mojito test app .

/Users/frankfa/.nvm/v0.6.21/lib/node_modules/mojito/lib/store.server.js:1261
            posls = this.selector.getAllPOSLs();
                                  ^
TypeError: Cannot call method 'getAllPOSLs' of undefined
    at ResourceStore.resolveResourceVersions (/Users/frankfa/.nvm/v0.6.21/lib/node_modules/mojito/lib/store.server.js:1261:35)
    at ResourceStore.preload (/Users/frankfa/.nvm/v0.6.21/lib/node_modules/mojito/lib/store.server.js:339:18)
    at /Users/frankfa/.nvm/v0.6.21/lib/node_modules/mojito/lib/app/commands/test.js:709:19
    at /Users/frankfa/.nvm/v0.6.21/lib/node_modules/mojito/lib/app/commands/test.js:808:9
    at Object.run (/Users/frankfa/.nvm/v0.6.21/lib/node_modules/mojito/lib/app/commands/test.js:645:9)
    at main (/Users/frankfa/.nvm/v0.6.21/lib/node_modules/mojito/lib/management/cli.js:125:13)
    at Object.<anonymous> (/Users/frankfa/.nvm/v0.6.21/lib/node_modules/mojito/lib/management/cli.js:137:1)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)

After fixing package.json to depend on mojito@0.4.0 and running npm install . again, mojito test does not crash anymore.

**Comment by FabianFrank** [comment]
I would recommend that every time we make compatibility breaking changes, we have to increment the dependency in the skeletons. So that all apps created with mojito@0.4.x should depend on mojito >=0.4.0 or maybe even 0.4.x.

**Comment by isao** [comment]
good idea-- we should modify the archtype logic to use the major-minor-x version number in use.

**Comment by FabianFrank** [comment]
@drewfish Do you think it makes sense to automatically pick the right mojito version depending on the mojito version that is currently active at run time instead of hardocding the version in the archetype? I was just looking at how to fix this and I think we could do this by reusing some code from the version command implementation. Let me know if you think this is a good idea and I can send the PR.

**Comment by drewfish** [comment]
@FabianFrank I was thinking the same thing.  I think fixing this will require the following (all in `store.server.js`):
- early during `preload()`, we need to calculate the currently-running Mojito's version
  - should go in `this._config.mojitoVersion` (already exists)
  - should come from `this._config.mojitoRoot` + `package.json`
  - _don't_ use `_preloadPackage()`, since that has significant side effects
- in `_preloadPackage()` when `info.pkg.name` is `'mojito`, check whether `info.pkg.version` matches `this._config.mojitoVersion`
  - if doesn't match, skip that package at least, probably emit a warning, perhaps emit an error

**Comment by isao** [comment]
heh, Fabian mentioned that earlier, and I restated it not fully noticing..

Can't we just load the mojito version from package.json and pass the major/minor version to template used by commands/create.js ?

**Comment by drewfish** [comment]
@isao Sure, but I think there is a runtime issue as well.  If global-mojito is run, and the local-mojito is a different version, mojito can/should detect that and give a warning/error.  That's what my big suggestion was about.

**Comment by bigfatsea** [comment]
I'm getting this error again. (osx 10.8, nodejs 0.8.16, npm 1.1.69)

/usr/local/lib/node_modules/mojito/lib/app/autoload/store.server.js:1480
            posls = this.selector.getAllPOSLs();
                                  ^
TypeError: Cannot call method 'getAllPOSLs' of undefined
    at ResourceStore.YUI.add.Y.extend.resolveResourceVersions (/usr/local/lib/node_modules/mojito/lib/app/autoload/store.server.js:1480:35)
    at ResourceStore.YUI.add.Y.extend.preload (/usr/local/lib/node_modules/mojito/lib/app/autoload/store.server.js:407:18)
    at Object.Store.createStore (/usr/local/lib/node_modules/mojito/lib/store.js:91:15)
    at new MojitoServer (/usr/local/lib/node_modules/mojito/lib/mojito.js:69:29)
    at Object.Mojito.createServer (/usr/local/lib/node_modules/mojito/lib/mojito.js:685:12)
    at Object.exports.run (/usr/local/lib/node_modules/mojito/lib/app/commands/start.js:88:18)
    at Function.CLI.run (/usr/local/lib/node_modules/mojito/lib/management/cli.js:176:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/mojito/bin/mojito:12:5)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)

**Comment by caridy** [comment]
@bigfatsea, this is a very old issue that was closed a while ago. Can you create a new issue and provide more data? including mojito version, repro case, etc.
