### ISSUE TITLE
.npmignore excludes lib/tests and test coverage jars

### ISSUE THREAD

**Issue by isao** [YahooArchive/mojito#431]
this breaks `mojito test -c app .`

**Comment by isao** [comment]
## steps to reproduce

with HEAD of develop d3df9426a13823d766dee519df02bf6e1f4f1c98

```
% npm rm -g mojito
% cd some/mojito app
% npm i path/to/mojito#d3df9426a13823d766dee519df02bf6e1f4f1c98
% ./node_modules/mojito/bin/mojito test app -c .
Instrumenting "/Users/isao/Desktop/newsboxes" for test coverage
    (this will take a while).

fs.js:420
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/Users/isao/Desktop/newsboxes/node_modules/mojito/lib/tests'
    at Object.lstatSync (fs.js:420:18)
    at Object.realpathSync (fs.js:878:23)
    at instrumentDirectory (/Users/isao/Desktop/newsboxes/node_modules/mojito/lib/app/commands/test.js:498:24)
    at /Users/isao/Desktop/newsboxes/node_modules/mojito/lib/app/commands/test.js:803:13
    at Object.run (/Users/isao/Desktop/newsboxes/node_modules/mojito/lib/app/commands/test.js:651:9)
    at main (/Users/isao/Desktop/newsboxes/node_modules/mojito/lib/management/cli.js:125:13)
    at Object.<anonymous> (/Users/isao/Desktop/newsboxes/node_modules/mojito/lib/management/cli.js:137:1)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
```
