### ISSUE TITLE
adding a package.json in an app/mojits/mojit directory causes 500 error

### ISSUE THREAD

**Issue by isao** [YahooArchive/mojito#609]
steps to reproduce
1. `mojito create app simple Simple`
2. `mojito create mojit simple Simple`
3. create file [Simple/mojits/Simple/package.json](https://gist.github.com/fef4f76b248e89eca9cb)
4. `mojito start`
5. http://localhost:8666/@Simple/index

expected result: browser displays "Mojito is working."

actual result: "Error: 500"

mojito log

```
[DEBUG] (1349892431757) static-handler: serving static path: /@Simple/index
[MOJITO] (1349892431764) server: request received
[MOJITO] (1349892431764) qeperf: request received
[MOJITO] (1349892431764) server: START
[MOJITO] (1349892431764) mojito-resource-store-adapter: resource store adapter init
[DEBUG] (1349892431764) mojito-dispatcher: Dispatcher created
[MOJITO] (1349892431764) qeperf: dispatching command for @Simple.index
[MOJITO] (1349892431764) qeperf: expanding partial mojit instance
[ERROR] (1349892431765) Server OutputHandler: Error 500: Unable to compute assets root for mojit "Simple". This usually happens when trying to run a mojit that does not exist.
Error: Unable to compute assets root for mojit "Simple". This usually happens when trying to run a mojit that does not exist.
    at RSAddonUrl.YUI.add.Y.extend.onGetMojitTypeDetails (/Users/isao/Repos/mojito/myfork/lib/app/addons/rs/url.server.js:162:23)
    at YUI.add.b.Subscriber._notify (/Users/isao/Repos/mojito/myfork/node_modules/yui/event-custom-base/event-custom-base-min.js:7:5911)
    at YUI.add.b.Subscriber.notify (/Users/isao/Repos/mojito/myfork/node_modules/yui/event-custom-base/event-custom-base-min.js:8:79)
    at YUI.add.b.CustomEvent._notify (/Users/isao/Repos/mojito/myfork/node_modules/yui/event-custom-base/event-custom-base-min.js:7:3997)
    at YUI.add.b.CustomEvent._procSubs (/Users/isao/Repos/mojito/myfork/node_modules/yui/event-custom-base/event-custom-base-min.js:7:4788)
    at YUI.add.a.fireComplex (/Users/isao/Repos/mojito/myfork/node_modules/yui/event-custom-complex/event-custom-complex-min.js:7:1378)
    at YUI.add.b.CustomEvent.fire (/Users/isao/Repos/mojito/myfork/node_modules/yui/event-custom-base/event-custom-base-min.js:7:4372)
    at ResourceStore.YUI.add.d.fire (/Users/isao/Repos/mojito/myfork/node_modules/yui/event-custom-base/event-custom-base-min.js:8:5302)
    at ResourceStore.YUI.add.Y.extend.getMojitTypeDetails (/Users/isao/Repos/mojito/myfork/lib/store.server.js:706:18)
    at ResourceStore.YUI.add.Y.extend.expandInstanceForEnv (/Users/isao/Repos/mojito/myfork/lib/store.server.js:570:22)
[INFO]  (1349892431769) server output adapter: done
```

**Comment by isao** [comment]
error on my part? problem may be with archtypes I'm working with. Retesting on head of develop seems ok. Closing

**Comment by isao** [comment]
sorry for the flip-flop, the problem does indeed exist.

**Comment by isao** [comment]
ahh. not my day. error caused by mis-match of mojit name and mojit's package.json name.

sorry for the noise, closing for real.
