### ISSUE TITLE
`mojito test mojit -c ./mojits` broken

### ISSUE THREAD

**Issue by isao** [YahooArchive/mojito#724]
mojit tests run as expected without the -c coverage flag, but on 0.4.8-128-g14e96cc (develop):

```
% cd examples/newsboxes/
% mojito test -c mojit mojits/
Instrumenting "/Users/isao/Repos/mojito/myfork/examples/newsboxes/mojits" for test coverage
    (this will take a while).

fs.js:500
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/private/tmp/mojito-lib-inst/lib'
    at Object.fs.readdirSync (fs.js:500:18)
    at walkDir (/Users/isao/Repos/mojito/myfork/lib/management/yui-module-configurator.js:24:20)
    at module.exports (/Users/isao/Repos/mojito/myfork/lib/management/yui-module-configurator.js:127:9)
    at testRunner (/Users/isao/Repos/mojito/myfork/lib/app/commands/test.js:681:29)
    at targetMojitoPath (/Users/isao/Repos/mojito/myfork/lib/app/commands/test.js:803:17)
    at /Users/isao/Repos/mojito/myfork/lib/app/commands/test.js:588:17
    at ChildProcess.exithandler (child_process.js:538:7)
    at ChildProcess.EventEmitter.emit (events.js:99:17)
    at maybeClose (child_process.js:638:16)
    at Socket.ChildProcess.spawn.stdin (child_process.js:815:11)
```

**Comment by isao** [comment]
fixed by 0bdde0f35eb14973ff02c006eaa49b34bde9a8b4
